// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oupixjxyjkcwqljtadiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91cGl4anh5amtjd3FsanRhZGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzAzMDAsImV4cCI6MjA3NDY0NjMwMH0.2Qqr-1LBU2J5LrC8wLP_P0a-9IAzLr2YPxUEPclDwWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});